.PHONY: wasm
wasm:
	mkdir -p output/wasm
	cd wasm && GOARCH=wasm GOOS=js go build -ldflags="-s -w" -o ../output/wasm/rsa.wasm main.go
	cp $(GOROOT)/misc/wasm/wasm_exec.js  output/wasm/wasm_exec.js
	cp output/wasm/rsa.wasm wasm/sample/public/rsa.wasm
	cp output/wasm/wasm_exec.js  wasm/sample/public/wasm_exec.js