// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConvertJWTRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsConvertJWTRequest(buf []byte, offset flatbuffers.UOffsetT) *ConvertJWTRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConvertJWTRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishConvertJWTRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConvertJWTRequest(buf []byte, offset flatbuffers.UOffsetT) *ConvertJWTRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConvertJWTRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConvertJWTRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConvertJWTRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConvertJWTRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConvertJWTRequest) Data() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConvertJWTRequest) KeyId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConvertJWTRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ConvertJWTRequestAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func ConvertJWTRequestAddKeyId(builder *flatbuffers.Builder, keyId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(keyId), 0)
}
func ConvertJWTRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
