// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConvertKeyPairRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsConvertKeyPairRequest(buf []byte, offset flatbuffers.UOffsetT) *ConvertKeyPairRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConvertKeyPairRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsConvertKeyPairRequest(buf []byte, offset flatbuffers.UOffsetT) *ConvertKeyPairRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConvertKeyPairRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ConvertKeyPairRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConvertKeyPairRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConvertKeyPairRequest) PrivateKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConvertKeyPairRequest) Certificate() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConvertKeyPairRequest) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConvertKeyPairRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ConvertKeyPairRequestAddPrivateKey(builder *flatbuffers.Builder, privateKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(privateKey), 0)
}
func ConvertKeyPairRequestAddCertificate(builder *flatbuffers.Builder, certificate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(certificate), 0)
}
func ConvertKeyPairRequestAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(password), 0)
}
func ConvertKeyPairRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
