// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DecryptPKCS1v15BytesRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsDecryptPKCS1v15BytesRequest(buf []byte, offset flatbuffers.UOffsetT) *DecryptPKCS1v15BytesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DecryptPKCS1v15BytesRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDecryptPKCS1v15BytesRequest(buf []byte, offset flatbuffers.UOffsetT) *DecryptPKCS1v15BytesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DecryptPKCS1v15BytesRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DecryptPKCS1v15BytesRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DecryptPKCS1v15BytesRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DecryptPKCS1v15BytesRequest) Ciphertext(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *DecryptPKCS1v15BytesRequest) CiphertextLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DecryptPKCS1v15BytesRequest) CiphertextBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DecryptPKCS1v15BytesRequest) MutateCiphertext(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *DecryptPKCS1v15BytesRequest) PrivateKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DecryptPKCS1v15BytesRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DecryptPKCS1v15BytesRequestAddCiphertext(builder *flatbuffers.Builder, ciphertext flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ciphertext), 0)
}
func DecryptPKCS1v15BytesRequestStartCiphertextVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func DecryptPKCS1v15BytesRequestAddPrivateKey(builder *flatbuffers.Builder, privateKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(privateKey), 0)
}
func DecryptPKCS1v15BytesRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
