// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EncryptPKCS1v15Request struct {
	_tab flatbuffers.Table
}

func GetRootAsEncryptPKCS1v15Request(buf []byte, offset flatbuffers.UOffsetT) *EncryptPKCS1v15Request {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EncryptPKCS1v15Request{}
	x.Init(buf, n+offset)
	return x
}

func FinishEncryptPKCS1v15RequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEncryptPKCS1v15Request(buf []byte, offset flatbuffers.UOffsetT) *EncryptPKCS1v15Request {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EncryptPKCS1v15Request{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEncryptPKCS1v15RequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EncryptPKCS1v15Request) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EncryptPKCS1v15Request) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EncryptPKCS1v15Request) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EncryptPKCS1v15Request) PublicKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func EncryptPKCS1v15RequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func EncryptPKCS1v15RequestAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(message), 0)
}
func EncryptPKCS1v15RequestAddPublicKey(builder *flatbuffers.Builder, publicKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(publicKey), 0)
}
func EncryptPKCS1v15RequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
