// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetadataPublicKeyRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsMetadataPublicKeyRequest(buf []byte, offset flatbuffers.UOffsetT) *MetadataPublicKeyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetadataPublicKeyRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetadataPublicKeyRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetadataPublicKeyRequest(buf []byte, offset flatbuffers.UOffsetT) *MetadataPublicKeyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetadataPublicKeyRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetadataPublicKeyRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetadataPublicKeyRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetadataPublicKeyRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetadataPublicKeyRequest) PublicKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetadataPublicKeyRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetadataPublicKeyRequestAddPublicKey(builder *flatbuffers.Builder, publicKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(publicKey), 0)
}
func MetadataPublicKeyRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
