// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type PEMCipher int32

const (
	PEMCipherDES    PEMCipher = 0
	PEMCipherD3DES  PEMCipher = 1
	PEMCipherAES128 PEMCipher = 2
	PEMCipherAES192 PEMCipher = 3
	PEMCipherAES256 PEMCipher = 4
)

var EnumNamesPEMCipher = map[PEMCipher]string{
	PEMCipherDES:    "DES",
	PEMCipherD3DES:  "D3DES",
	PEMCipherAES128: "AES128",
	PEMCipherAES192: "AES192",
	PEMCipherAES256: "AES256",
}

var EnumValuesPEMCipher = map[string]PEMCipher{
	"DES":    PEMCipherDES,
	"D3DES":  PEMCipherD3DES,
	"AES128": PEMCipherAES128,
	"AES192": PEMCipherAES192,
	"AES256": PEMCipherAES256,
}

func (v PEMCipher) String() string {
	if s, ok := EnumNamesPEMCipher[v]; ok {
		return s
	}
	return "PEMCipher(" + strconv.FormatInt(int64(v), 10) + ")"
}
