// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PrivateKeyInfoResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsPrivateKeyInfoResponse(buf []byte, offset flatbuffers.UOffsetT) *PrivateKeyInfoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PrivateKeyInfoResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPrivateKeyInfoResponse(buf []byte, offset flatbuffers.UOffsetT) *PrivateKeyInfoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PrivateKeyInfoResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *PrivateKeyInfoResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PrivateKeyInfoResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PrivateKeyInfoResponse) Output(obj *PrivateKeyInfo) *PrivateKeyInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PrivateKeyInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PrivateKeyInfoResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PrivateKeyInfoResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PrivateKeyInfoResponseAddOutput(builder *flatbuffers.Builder, output flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(output), 0)
}
func PrivateKeyInfoResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(error), 0)
}
func PrivateKeyInfoResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
