// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VerifyPSSRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsVerifyPSSRequest(buf []byte, offset flatbuffers.UOffsetT) *VerifyPSSRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VerifyPSSRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsVerifyPSSRequest(buf []byte, offset flatbuffers.UOffsetT) *VerifyPSSRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VerifyPSSRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *VerifyPSSRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VerifyPSSRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VerifyPSSRequest) Signature() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *VerifyPSSRequest) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *VerifyPSSRequest) Hash() Hash {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return Hash(rcv._tab.GetInt32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VerifyPSSRequest) MutateHash(n Hash) bool {
	return rcv._tab.MutateInt32Slot(8, int32(n))
}

func (rcv *VerifyPSSRequest) SaltLength() SaltLength {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return SaltLength(rcv._tab.GetInt32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VerifyPSSRequest) MutateSaltLength(n SaltLength) bool {
	return rcv._tab.MutateInt32Slot(10, int32(n))
}

func (rcv *VerifyPSSRequest) PublicKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func VerifyPSSRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func VerifyPSSRequestAddSignature(builder *flatbuffers.Builder, signature flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(signature), 0)
}
func VerifyPSSRequestAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func VerifyPSSRequestAddHash(builder *flatbuffers.Builder, hash Hash) {
	builder.PrependInt32Slot(2, int32(hash), 0)
}
func VerifyPSSRequestAddSaltLength(builder *flatbuffers.Builder, saltLength SaltLength) {
	builder.PrependInt32Slot(3, int32(saltLength), 0)
}
func VerifyPSSRequestAddPublicKey(builder *flatbuffers.Builder, publicKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(publicKey), 0)
}
func VerifyPSSRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
